name = "slb"
main = "src/worker.ts"
compatibility_date = "2025-08-10"

[dev]
port = 8787

# Production environment variables can be set via wrangler vars:set command
# or uncommented here for default values
# [vars]
# ORIGINS = "https://api1.example.com,https://api2.example.com"
# ORIGIN_TIMEOUT_MS = "8000"
# RETRIES = "1"
# FAIL_STATUSES = "521,522,523,504,500"
# LB_DIAG_PATH = "/__lb/health"